#!/bin/bash
# -*- Bash -*- #
#
# Copyright 2020 Carlos Bocanegra.
# The Genesys Lab, Northeastern University, Boston, MA
#
#

# install prerequisite
sudo apt-get install libpcre3-dev

# download swig 3.0.12
(cd /tmp; wget -O swig-3.0.12.tar.gz https://downloads.sourceforge.net/project/swig/swig/swig-3.0.12/swig-3.0.12.tar.gz?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fswig%2Ffiles%2Fswig%2Fswig-3.0.12%2Fswig-3.0.12.tar.gz%2Fdownload&ts=1486782132&use_mirror=superb-sea2)

# extract and configure
(cd /tmp; tar xf swig-3.0.12.tar.gz)

# configure
(cd /tmp/swig-3.0.12; ./configure --prefix=/usr)

# build
(cd /tmp/swig-3.0.12; make -j 4)

# install
(cd /tmp/swig-3.0.12; sudo make install)

# check version reported
swig -version
